language: node_js
node_js:
- stable
- '10'
- '9'
- '8'
- '8.6'
notifications:
  email: false
deploy:
  provider: npm
  email: edjopato@gmail.com
  api_key:
    secure: hRCs2jFcxEBaJ7/auqUYcQnw7XRWrqA5BllANB2oqAm6EHsjvMDfkNIw9UmQKiFQA23SbOqNXHdPMzxR2jA34Ei6sph6IU0xSaUSxNAHCG6fSnrHQtAjWlBi1TdLy9cQzlJ+W5X9oQfIChzL8nBgBFeZZ57Bzrteb/XC1+FdoQm6O22m6C4peJRqenDnr8KHEp3Xj1m607URAize7WjI/Gk2d1SDFKJCPhY0Svyz1TW9ws1aUkorwPHNIDc/Rtk6mBme0R5tv/sNqWu5f4Yg1d0flX69RIaUWK0vvSGkpi6SFPi1ionfEXsivWKiDL1enRHi9suZne1WACWEIvrwUU0itdSIMkMBamBfWmexUMocww9aWRwmBXrW30aOOhMnhHgDA/RwOC/8h6RtKa2tTcuFDbZbiOgrENqle4Ix8IyDr8skV59wEVrzyPVx5m5MIn3W9Vi/y0o51PIvyawe7kct5qwZ/sstLhtXM620FscxPRU2hzkgGrzXLzNV5Ya6THV+dPsoNJ0+IAC94UQHgWM7WXvOjFO87aMCC7GVVYSxg8AfqEIk/uXogAyy91EvSCMCN/MsrjT/eTLHR0+Ps7P5fs9eIqDJEkpNCWNkyArEzzL3/gDYFb6LdgZ1UraejJ4twJSt0y4qRGVxYWMMAuokjTtFHRlhtsSmm1qv5/o=
  on:
    tags: true
    repo: EdJoPaTo/resilio-sync-watch-config
